require_relative 'paperclip_dynamic_edit/paperclip_processors/dynamic_edit'
require_relative 'paperclip_dynamic_edit/dynamic_editable'
require_relative 'paperclip_dynamic_edit/attachment'

module PaperclipDynamicEdit
end
